# This file was generated by GoReleaser. DO NOT EDIT.
cask "meowg1k" do
  desc "Your purr-sonal AI sidekick for coding, writing, and automating anything — right from your terminal."
  homepage "https://github.com/retran/meowg1k"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "meow"
  manpage "docs/man/meow.1"
  manpage "docs/man/meow-generate.1"
  manpage "docs/man/meow-version.1"
  manpage "docs/man/meow-config.5"
  manpage "docs/man/meow-security.7"

  on_macos do
    on_intel do
      url "https://github.com/retran/meowg1k/releases/download/v0.1.0/meowg1k_0.1.0_darwin_amd64.tar.gz"
      sha256 "d6ae8298eb6f1336d6ea94b7bfd4c83fdb76c004379aec49c735fa25a4e28811"
    end
    on_arm do
      url "https://github.com/retran/meowg1k/releases/download/v0.1.0/meowg1k_0.1.0_darwin_arm64.tar.gz"
      sha256 "11bdfcbd848580b78380880a6cb0aa7a25b96f9e71b76b2a3ecf2ff1a3130d5e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/retran/meowg1k/releases/download/v0.1.0/meowg1k_0.1.0_linux_amd64.tar.gz"
      sha256 "1fd46c1d68e133ec34bdf287487e0992480f9b54a454c145f5a2f41794ccd627"
    end
    on_arm do
      url "https://github.com/retran/meowg1k/releases/download/v0.1.0/meowg1k_0.1.0_linux_arm64.tar.gz"
      sha256 "445822894a580e467aac6bfa3d0e7a461871d2a2bc331b4d8cbfda0724d1363d"
    end
  end

  caveats do
    "🐾 Configuration & Providers"
    "----------------------------"
    "• Gemini (cloud):"
    "    Set API key:"
    "      export MEOW_GEMINI_API_KEY="your_api_key""
    ""
    "    Quick start:"
    "      cat main.go | meow generate -m gemini-2.5-pro -p "Explain this code""
    "      cat component.js | meow g -m gemini-2.5-flash -p "Refactor for performance""
    "      cat utils.go | meow g -m gemini-2.5-pro -s "You are a senior Go engineer reviewing code for concurrency issues" -p "Check this code for potential race conditions""
    ""
    "    Defaults via config:"
    "      generate:"
    "        defaultProvider: "gemini""
    "        defaultModel: "gemini-2.5-flash""
    "        defaultTimeout: "5m""
    ""
    "• LLaMA (local llama.cpp):"
    "    Start server separately, then connect (model is chosen by server):"
    "      meow g -P llama -u http://127.0.0.1:8080 -p "Summarize this code""
    ""
    "🧱 Tasks (reusable prompts)"
    "---------------------------"
    "  Example user config (~/.config/meowg1k/config.yaml):"
    "    generate:"
    "      tasks:"
    "        pytest-gemini:"
    "          provider: "gemini""
    "          model: "gemini-2.5-pro""
    "          systemPrompt: "You are an expert Python TDD developer.""
    "          userPrompt: "Write a complete pytest test file for the following code.""
    "        refactor-llama:"
    "          provider: "llama""
    "          llamaBaseURL: "http://127.0.0.1:8080""
    "          systemPrompt: "You write clean, performant Rust.""
    "          userPrompt: "Refactor for clarity and speed.""
    ""
    "  Run:"
    "    cat app.py | meow g -t pytest-gemini"
    "    cat main.rs | meow g -t refactor-llama"
    ""
    "📂 Config files (override order)"
    "--------------------------------"
    "  1) Project: ./.meowg1k/config.yaml"
    "  2) User:    ~/.config/meowg1k/config.yaml"
    ""
    "📖 Man pages"
    "-----------"
    "  man meow"
    "  man meow-generate"
    "  man 5 meow-config"
    "  man 7 meow-security"
  end

  # No zap stanza required
end
