# This file was generated by GoReleaser. DO NOT EDIT.
cask "meowg1k" do
  desc "Your purr-sonal AI sidekick for coding, writing, and automating anything — right from your terminal."
  homepage "https://github.com/retran/meowg1k"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "meow"
  manpage "docs/man/meow.1"
  manpage "docs/man/meow-generate.1"
  manpage "docs/man/meow-version.1"
  manpage "docs/man/meow-config.5"
  manpage "docs/man/meow-security.7"

  on_macos do
    on_intel do
      url "https://github.com/retran/meowg1k/releases/download/v0.1.0/meowg1k_0.1.0_darwin_amd64.tar.gz"
      sha256 "9e0c3fb4dc84b2f129c255622a1b173a9d51684dab178c980980d84d428aa073"
    end
    on_arm do
      url "https://github.com/retran/meowg1k/releases/download/v0.1.0/meowg1k_0.1.0_darwin_arm64.tar.gz"
      sha256 "b9033ac3474253de2bebbc837f9a79e7320e716020ea50d429e488ce5e19ae4c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/retran/meowg1k/releases/download/v0.1.0/meowg1k_0.1.0_linux_amd64.tar.gz"
      sha256 "dc59efd456d96f1f19c15414efbc81cb409bbe0bc08761be9986fd6c9d5b7482"
    end
    on_arm do
      url "https://github.com/retran/meowg1k/releases/download/v0.1.0/meowg1k_0.1.0_linux_arm64.tar.gz"
      sha256 "7b79273c106d6437f548a1059a36c21176fdf17019727ff44ef5cfe551b575b4"
    end
  end

  caveats do
    "🐾 Configuration & Providers"
    "----------------------------"
    "• Gemini (cloud):"
    "    Set API key:"
    "      export MEOW_GEMINI_API_KEY='your_api_key'"
    ""
    "    Quick start:"
    "      cat main.go | meow generate -m gemini-2.5-pro -p 'Explain this code'"
    "      cat component.js | meow g -m gemini-2.5-flash -p 'Refactor for performance'"
    "      cat utils.go | meow g -m gemini-2.5-pro -s 'You are a senior Go engineer reviewing code for concurrency issues' -p 'Check this code for potential race conditions'"
    ""
    "    Defaults via config:"
    "      generate:"
    "        defaultProvider: gemini"
    "        defaultModel: gemini-2.5-flash"
    "        defaultTimeout: 5m"
    ""
    "• LLaMA (local llama.cpp):"
    "    Start server separately, then connect (model is chosen by server):"
    "      meow g -P llama -u http://127.0.0.1:8080 -p 'Summarize this code'"
    ""
    "🧱 Tasks (reusable prompts)"
    "---------------------------"
    "  Example user config (~/.config/meowg1k/config.yaml):"
    "    generate:"
    "      tasks:"
    "        pytest-gemini:"
    "          provider: gemini"
    "          model: gemini-2.5-pro"
    "          systemPrompt: You are an expert Python TDD developer."
    "          userPrompt: Write a complete pytest test file for the following code."
    "        refactor-llama:"
    "          provider: llama"
    "          llamaBaseURL: http://127.0.0.1:8080"
    "          systemPrompt: You write clean, performant Rust."
    "          userPrompt: Refactor for clarity and speed."
    ""
    "  Run:"
    "    cat app.py | meow g -t pytest-gemini"
    "    cat main.rs | meow g -t refactor-llama"
    ""
    "📂 Config files (override order)"
    "--------------------------------"
    "  1) Project: ./.meowg1k/config.yaml"
    "  2) User:    ~/.config/meowg1k/config.yaml"
    ""
    "📖 Man pages"
    "-----------"
    "  man meow"
    "  man meow-generate"
    "  man 5 meow-config"
    "  man 7 meow-security"
  end

  # No zap stanza required
end
